/** Stable invalid reasons for POST /api/boarding/validate (S2-T2). */
export const BOARDING_VALIDATION_REASONS = {
  INVALID_TOKEN: "INVALID_TOKEN",
  EXPIRED_TOKEN: "EXPIRED_TOKEN",
  INVALID_TYPE: "INVALID_TYPE",
  INVALID_PAYLOAD: "INVALID_PAYLOAD",
  RESERVATION_NOT_FOUND: "RESERVATION_NOT_FOUND",
  TOKEN_REVOKED: "TOKEN_REVOKED",
  RESERVATION_NOT_CONFIRMED: "RESERVATION_NOT_CONFIRMED",
  TRIP_DISABLED: "TRIP_DISABLED",
  BOARDING_NOT_STARTED: "BOARDING_NOT_STARTED",
  BOARDING_CLOSED: "BOARDING_CLOSED",
  TRIP_COMPLETED: "TRIP_COMPLETED",
  TRIP_CANCELLED: "TRIP_CANCELLED",
  BOARDING_WINDOW_EXPIRED: "BOARDING_WINDOW_EXPIRED",
  PAYMENT_NOT_SUCCEEDED: "PAYMENT_NOT_SUCCEEDED",
  INTERNAL_VALIDATION_ERROR: "INTERNAL_VALIDATION_ERROR",
} as const;

export type BoardingValidationReason =
  (typeof BOARDING_VALIDATION_REASONS)[keyof typeof BOARDING_VALIDATION_REASONS];
